/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import MODELO.ah4DAORelacional;
import POO.sucursalesPOO;
import POO.vendedoresPOO;
import img.TextPrompt;
import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class upVen extends javax.swing.JFrame {

    /**
     * Creates new form upVen
     */
    LinkedList<String> sucu = new LinkedList<>();
    public upVen() {
        initComponents();
        this.setLocationRelativeTo(null);
        TextPrompt tf1 = new TextPrompt("Nombre: ",nomven);
        TextPrompt tf2 = new TextPrompt("Caja: ",cajaven);
        TextPrompt tf3 = new TextPrompt("Ventas: ",ventasven);
        TextPrompt tf4 = new TextPrompt("Contraseña: ",conven);
        genero.add(mas);
        genero.add(fem);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genero = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        fem = new javax.swing.JRadioButton();
        ventasven = new javax.swing.JTextField();
        cajaven = new javax.swing.JTextField();
        conven = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomven = new javax.swing.JTextField();
        mas = new javax.swing.JRadioButton();
        codven = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(195, 229, 127));

        fem.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        fem.setText("Femenino");

        ventasven.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ventasven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ventasvenKeyTyped(evt);
            }
        });

        cajaven.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cajaven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajavenActionPerformed(evt);
            }
        });
        cajaven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajavenKeyTyped(evt);
            }
        });

        conven.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sellers_man_real_state_home_house_icon_230958.png"))); // NOI18N

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarSesion.png"))); // NOI18N
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarSesion.png"))); // NOI18N
        jButton26.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarSesion.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        jLabel1.setText("Actualizar Vendedor");

        nomven.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nomven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomvenKeyTyped(evt);
            }
        });

        mas.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        mas.setText("Masculino");

        codven.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        codven.setEnabled(false);
        codven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codvenKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(fem))
                    .addComponent(conven)
                    .addComponent(ventasven)
                    .addComponent(nomven)
                    .addComponent(cajaven)
                    .addComponent(codven))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton26)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codven, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomven, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cajaven, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(ventasven, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fem)
                    .addComponent(mas))
                .addGap(18, 18, 18)
                .addComponent(conven, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton26)
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventasvenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ventasvenKeyTyped
        ventasven.setBackground(new Color (255,255,255));
    }//GEN-LAST:event_ventasvenKeyTyped

    private void cajavenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajavenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajavenActionPerformed

    private void cajavenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajavenKeyTyped
        cajaven.setBackground(new Color (255,255,255));
    }//GEN-LAST:event_cajavenKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(nomven.getText().isEmpty()||cajaven.getText().isEmpty()||ventasven.getText().isEmpty()
            ||(mas.isSelected()==false &&fem.isSelected()==false)||conven.getText().isEmpty()){

            JOptionPane.showMessageDialog(null, "DEBE LLENAR Y/O SELECCIONAR TODOS LOS CAMPOS");
            Color ca = new Color(255,160,160);
            if(nomven.getText().equals("")){
                nomven.setBackground(ca);
            }
            if(cajaven.getText().equals("")){
                cajaven.setBackground(ca);
            }
            if(ventasven.getText().equals("")){
                ventasven.setBackground(ca);
            }
            if(mas.isSelected()==false && fem.isSelected() == false){
                fem.setForeground(Color.red);
                mas.setForeground(Color.red);
            }
            if(conven.getText().equals("")){
                conven.setBackground(ca);
            }
        }else{
            modificar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        principal pr = new principal();
        pr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton26ActionPerformed

    private void nomvenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomvenKeyTyped
        nomven.setBackground(new Color (255,255,255));
    }//GEN-LAST:event_nomvenKeyTyped

    private void codvenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codvenKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codvenKeyTyped

    
    
    
    public void mostrar(int id){

        ah4DAORelacional ahd = new ah4DAORelacional();
        vendedoresPOO vp = ahd.obtenerVen(id);
  
        
        if(vp.getGenero().equals("M")){
            codven.setText(String.valueOf(vp.getId()));
            nomven.setText(String.valueOf(vp.getNombre()));
            cajaven.setText(String.valueOf(vp.getCaja()));
            ventasven.setText(String.valueOf(vp.getVentas()));
            mas.setSelected(true);
            fem.setSelected(false);
            conven.setText(vp.getPassword());
  
        }else if(vp.getGenero().equals("F")){
            codven.setText(String.valueOf(vp.getId()));
            nomven.setText(vp.getNombre());
            cajaven.setText(String.valueOf(vp.getCaja()));
            ventasven.setText(String.valueOf(vp.getVentas()));
            mas.setSelected(false);
            fem.setSelected(true);
            conven.setText(vp.getPassword());
      
        }
        
        
    }
    
    private void modificar(){
        
        if(mas.isSelected() == true){
           ah4DAORelacional ahd = new ah4DAORelacional();
           vendedoresPOO vp = new vendedoresPOO(Integer.parseInt(codven.getText()),
           nomven.getText(),Integer.parseInt(cajaven.getText()),Integer.parseInt(ventasven.getText()),
           "M",conven.getText());
           ahd.modificarVendedor(vp);
           principal pr = new principal();
           pr.setVisible(true);
           dispose();
           
        }else if (fem.isSelected() == true){
           ah4DAORelacional ahd = new ah4DAORelacional();
           vendedoresPOO vp = new vendedoresPOO(Integer.parseInt(codven.getText()),
           nomven.getText(),Integer.parseInt(cajaven.getText()),Integer.parseInt(ventasven.getText()),
           "F",conven.getText());
           ahd.modificarVendedor(vp);
           principal pr = new principal();
           pr.setVisible(true);
           dispose();
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(upVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(upVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(upVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new upVen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajaven;
    private javax.swing.JTextField codven;
    private javax.swing.JPasswordField conven;
    private javax.swing.JRadioButton fem;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton26;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mas;
    private javax.swing.JTextField nomven;
    private javax.swing.JTextField ventasven;
    // End of variables declaration//GEN-END:variables
}
